# Generated by Django 5.2.17 on 2026-09-03 18:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=320)),
                ("token", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("external_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signers",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("email",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "email"), name="unique_signer_email_per_document"
                    )
                ],
            },
        ),
    ]
