# Generated by Django 5.2.17 on 2026-09-03 16:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "api_token",
                    models.CharField(
                        help_text="ZapSign account API token. Write-only across the API: it is never serialized back in full and never reaches an automation endpoint (FR-002).",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ("name",),
            },
        ),
    ]
