# Generated by Django 5.2.17 on 2026-09-03 18:46

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "pdf_url",
                    models.URLField(
                        max_length=2048,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        choices=[
                            ("pending_integration", "Pending integration"),
                            ("submitted", "Submitted"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending_integration",
                        help_text="Our ZapSign hand-off lifecycle; drives the retry path (FR-010).",
                        max_length=32,
                    ),
                ),
                ("open_id", models.IntegerField(blank=True, null=True)),
                ("token", models.CharField(blank=True, default="", max_length=255)),
                ("external_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Signature status as reported by ZapSign; never computed locally (FR-013).",
                        max_length=64,
                    ),
                ),
                ("created_by", models.CharField(blank=True, default="", max_length=255)),
                ("last_provider_error", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Deleting a company with documents is refused rather than orphaning them.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"], name="documents_d_company_45ca0d_idx"
                    )
                ],
            },
        ),
    ]
