# Generated by Django 5.2.17 on 2026-09-03 19:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")], max_length=16
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("missing_topics", models.JSONField(blank=True, default=list)),
                (
                    "insights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Each entry is {"text": str, "risk": bool}.',
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("llm", "Model"),
                            ("regex", "Rule-based"),
                            ("llm+regex", "Model + rules"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_reason", models.CharField(blank=True, default="", max_length=255)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "document analyses",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["document", "-created_at"], name="documents_d_documen_427e9f_idx"
                    )
                ],
            },
        ),
    ]
